services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ulekare
      MARIADB_USER: ulekare
      MARIADB_PASSWORD: ulekare
    ports:
      - "${DB_HOST_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_HOST_PORT:-8000}:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ulekare
      DB_USERNAME: ulekare
      DB_PASSWORD: ulekare
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
